PrimeDAO/launch-contracts

- contracts/seed/Seed.sol
- test/seed.js
> removed not needed params

- contracts/seed/Seed.sol
- test/seed.js
branch 22 was merged with 19 so need to re-merge 19
content didn't change at all
> 22 add unique fee parameter for class (was merged with 19. need to merge into main)

- contracts/seed/Seed.sol
> 32 Missing check for success of tokens transfer

- contracts/seed/Seed.sol
> 53 Use memory instead of reading multiple times from storage

- package.json
> 59 Dependencies on deprecated version of OpenZeppelin

- contracts/seed/Seed.sol
closes <https://github.com/PrimeDAO/launch-contracts/issues/39>
> 39 Unused variables in ContributorClass

- contracts/seed/Seed.sol
> 51 Mark functions external where possible

- contracts/seed/Seed.sol
- package.json
- test/seed.js
closes <https://github.com/PrimeDAO/launch-contracts/issues/36>
here lint breaks
[conflicts resolved setup.seed.classes(0)](https://github.com/PrimeDAO/launch-contracts/pull/64/commits/19fd4cd22c77a6250f2f7d8494f9bb1df7ad5a4a) 
here and later package.json also edited and lint fixed
[fix?](https://github.com/PrimeDAO/launch-contracts/pull/64/commits/ea6392db590ddd252b18f638ff855857563530d8)
> 36 Unused state variables

- contracts/seed/Seed.sol
> 34  An attacker can diminish the amount of tokens available in a class

- contracts/seed/Seed.sol
> 31 Sale could be started before the contract is funded

- contracts/seed/Seed.sol
- test/seed.js
closes <https://github.com/PrimeDAO/launch-contracts/issues/35>
> 35 When maximum is reached, vestingStartTime is set to the current time for only a single class

- contracts/seed/Seed.sol
- test/seed.js
removed (which was in comments until last commit) last test, need to move it into new context in 16-branch. thus coverage will be 100%
closes #28 
probably it's better to solve merge conflicts closer to the end of merging branches, because for now, main-branch-code locally crashes tests of this branch.
> fix bug with feeRemainder

- contracts/seed/Seed.sol
- test/seed.js
> 27 fix bug with fee remainder

- test/seed.js
closes <https://github.com/PrimeDAO/launch-contracts/issues/67>
based on 16-add-tests-on-contributors-in-few-classes-simultanuosly
> 67 incorrect test variables

- hardhat.config.js
- package-lock.json
- tasks/seedManagement.js
- test/args/seed-test-args.json
Story details: https://app.shortcut.com/curvelabs/story/144
> feat: [sc-144] Create script for deploying Seeds

- package-lock.json
- package.json
- tasks/utils/gnosis.js
Story details: https://app.shortcut.com/curvelabs/story/147
> feat: [sc-147] Add Gnosis Safe task to Launch-Contracts repo

- lib/gnosis.js
Story details: https://app.shortcut.com/curvelabs/story/1412
> chore: [sc-1412] Update Goerli Safe API url

- contracts/seed/Seed.sol
- test/helpers/accounts/signers.js
- test/helpers/contracts/seed/Seed.js
- test/helpers/fixture.js
- test/seed.spec.js
- followed recommendations
- merged 2 audit report points, because both address the same part of the code
> Bug/sc 1466/audit finding s1 & s8

- contracts/seed/Seed.sol
- test/helpers/contracts/seed/Seed.js
Note: this update of the code will lead to a change in the FE, once the new contracts are deployed. One parameter of the function call `claim()` need to be removed
@hiaux0
> Bug/sc 1470/audit finding s3

- contracts/seed/Seed.sol
- test/seed.spec.js
- followed audit recommendation
- Add condition that sets `vestingStartTime` to the current time if Seed has been closed before is is complete
- Moved require statements to a modifier
- Adapted tests and added tests
> Chore/sc 1474/audit finding s5

- contracts/seed/SeedFactory.sol
- deploy/00_deploy_seed_contracts.js
- test/helpers/contracts/ContractDeployer.js
- test/helpers/contracts/contracts.js
- test/helpers/contracts/seed/builders/SeedBuilder.js
- test/helpers/contracts/seed/builders/SeedFactoryBuilder.js
- test/helpers/fixture.js
- test/helpers/params/constructParams.js
- test/seedFactory.spec.js
- followed audit recommendations (see SC issue)
- Adapted test file and helpers to accommodate change in `SeedFactory`
- Adapt deploy script to remove the `setMasterCopy()` function call
> Chore/sc 1492/audit finding f1

- contracts/seed/Seed.sol
- contracts/seed/SeedFactory.sol
- docs/PrimeDAOErrors.md
- test/seed.spec.js
- test/seedFactory.spec.js
- Added Error codes to `PrimeDAOErrors.md` document
- Replaced error message string with error code in the contract
- Adapted tests to reflect changes
I did not follow the audit recommendations because creating the custom errors is a more structural change. This will be done in a later development cycle
> chore: [sc-1460] Audit Finding: G1

- contracts/seed/Seed.sol
- docs/PrimeDAOErrors.md
- test/seed.spec.js
- Implement recommended change also for the contributor class cap
> fix: [sc-1472] Audit Finding: S4

- contracts/seed/Seed.sol
- Moved require statement to after the `_fundingAmount` is updated. This change was suggested by the auditors
> chore: [sc-1761] Move require in function buy

- contracts/seed/SeedFactoryNoAccessControl.sol
- test/helpers/constants/constants.js
- test/helpers/contracts/ContractDeployer.js
- test/helpers/contracts/seed/builders/SeedFactoryBuilder.js
- test/helpers/fixture.js
- test/helpers/params/constructParams.js
- test/seedFactory.spec.js
- Adapted SeedFactory
- Adapt test helpers
- Add test
> feat: [sc-1870] Adapt SeedFactory for no-Safe flow

- lib/params/safeAddresses.js
https://safe.celo.org/mainnet:0x9C3465Ea2e3Fb3AEc3bDFd124d73FcCe72F71F01/address-book
`0x9C3465Ea2e3Fb3AEc3bDFd124d73FcCe72F71F01`
> chore: [sc-1209] update safe address on celo
